
export const BEER_ACTION_TYPE = {
    GET_ALL_BEERS_REQUEST: 'GET_ALL_BEERS_REQUEST',
    GET_ALL_BEERS_SUCCEED: 'GET_ALL_BEERS_SUCCEED',
    GET_CERTAIN_BEER: 'GET_CERTAIN_BEER',
    SET_BEERS_PER_PAGE: 'SET_BEERS_PER_PAGE',
    GET_BEERS_BY_PAGE: 'GET_BEERS_BY_PAGE',
    REQUEST_ERROR_STATE: 'REQUEST_ERROR_STATE'
};

export const FAVOURITE_ACTION_TYPE = {
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    SET_NEW_FAVOURITE_LIST: 'SET_NEW_FAVOURITE_LIST'
};

export const LOADING_ACTION_TYPE = {
    SET_LOADING_STATE: 'SET_LOADING_STATE'
};

// export const SEARCH_ACTION_TYPE = {
//
// };
