
export const BEER_ACTION_TYPE = {
    GET_ALL_BEERS_REQUEST: 'GET_ALL_BEERS_REQUEST',
    GET_ALL_BEERS_SUCCEED: 'GET_ALL_BEERS_SUCCEED',
    GET_CERTAIN_BEER: 'GET_CERTAIN_BEER',
    GET_CERTAIN_BEER_SUCCEED: 'GET_CERTAIN_BEER_SUCCEED',
    GET_RANDOM_BEER: 'GET_RANDOM_BEER',
    GET_RANDOM_BEER_SUCCEED: 'GET_RANDOM_BEER_SUCCEED',
    CLEAR_CERTAIN_BEER: 'CLEAR_CERTAIN_BEER',
    PAGINATION_REQUEST: 'PAGINATION_REQUEST',
    SET_BEERS_PAGINATION: 'SET_BEERS_PAGINATION',
    REQUEST_ERROR_STATE: 'REQUEST_ERROR_STATE'
};

export const FAVOURITE_ACTION_TYPE = {
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    SET_NEW_FAVOURITE_LIST: 'SET_NEW_FAVOURITE_LIST'
};

export const LOADING_ACTION_TYPE = {
    SET_LOADING_STATE: 'SET_LOADING_STATE'
};

// export const SEARCH_ACTION_TYPE = {
//
// };
