
export const BEER_ACTION_TYPE = {
    GET_ALL_BEERS_REQUEST: 'GET_ALL_BEERS_REQUEST',
    GET_ALL_BEERS_SUCCEED: 'GET_ALL_BEERS_SUCCEED',
    GET_CERTAIN_BEER: 'GET_CERTAIN_BEER',
    GET_CERTAIN_BEER_SUCCEED: 'GET_CERTAIN_BEER_SUCCEED',
    GET_PAGINATION_BEER_SUCCEED: 'GET_PAGINATION_CERTAIN_BEER_SUCCEED',
    GET_RANDOM_BEER: 'GET_RANDOM_BEER',
    GET_RANDOM_BEER_SUCCEED: 'GET_RANDOM_BEER_SUCCEED',
    CLEAR_CERTAIN_BEER: 'CLEAR_CERTAIN_BEER',
    INFINITE_SCROLL_BEERS: 'INFINITE_SCROLL_BEERS',
    PAGINATION_REQUEST: 'PAGINATION_REQUEST',
    SET_BEERS_PAGINATION: 'SET_BEERS_PAGINATION',
    REQUEST_ERROR_STATE: 'REQUEST_ERROR_STATE'
};

export const FAVOURITE_ACTION_TYPE = {
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    ADDED_FAVOURITE_LIST_SUCCEED: 'ADDED_FAVOURITE_LIST_SUCCEED',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    REMOVE_FROM_FAVOURITES_SUCCEED: 'REMOVE_FROM_FAVOURITES_SUCCEED',
    CLEAR_FAVOURITE_LIST: 'CLEAR_FAVOURITE_LIST',
};

export const LOADING_ACTION_TYPE = {
    SET_LOADING_STATE: 'SET_LOADING_STATE'
};

// export const SEARCH_ACTION_TYPE = {
//
// };
